### ISSUE TITLE
scans not starting anymore

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara-ci-issues#12]
It just never finishes any of the tasks:

<img width="654" alt="Bildschirmfoto 2022-03-01 um 22 49 03" src="https://user-images.githubusercontent.com/827205/156254714-3075cdae-2ca2-4c31-a091-1850bee49450.png">

**Comment by Zohiartze** [comment]
Catched and patched, we deployed a new version yesterday with the fix, but the pending tasks will never end (in reality they never started) so I'm afraid you will have to push some changes for them to start again.

**Comment by DanielRuf** [comment]
Thanks. I have force-pushed the relevant commit so that the pending job does not appear anymore and triggered a new one. It works now.
