### ISSUE TITLE
Add Information where Results are Supposed to Appear to Documentation

### ISSUE THREAD

**Issue by baderj** [VirusTotal/yara-ci-issues#13]
The whole documentation of how to install and configure YARA-CI is great. However, I feel like this sentence should be followed by some more details:

> Once the application is installed, your YARA rules will be analyzed on every commit you make to the repository.

In particular: Where can you see the results of the analysis? I don't see any results and also don't receive emails. Since the installation is literally just takes a few clicks, it would be great to also have a short pointer where to look for the results.

**Comment by Zohiartze** [comment]
Hi @baderj you can see the results in GitHub itself, along with the results of the other checks that are run on each commit:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/40301647/164041950-96931dc0-8caa-413b-99c5-19f4469ebdcb.png">

We have updated [the documentation](https://yara-ci.cloud.virustotal.com/installation/installation/) to clarity this.

**Comment by baderj** [comment]
Ah yes of course, thank you very much. I completely overlooked the small icon next to the commit hash and kept looking under Actions. Your addition to the documentation is great and should and very helpful for people like me who don't know Github very well.

**Comment by Zohiartze** [comment]
You are welcome! It's easy to make assumptions while writing documentation, so thank you for pointing this weak point.
