### ISSUE TITLE
not triggered anymore

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara-ci-issues#14]
I have nothing changed and right now no new yara CI run is triggered.

**Comment by plusvic** [comment]
Thank you for the heads up. It should be working now.

**Comment by DanielRuf** [comment]
Confirmed, it works now. Thank you very much.

Closing as resolved.

**Comment by DanielRuf** [comment]
Reopening as it happens again.

A few minutes ago I had pushed commits to my repo. No yara CI check was triggered.

**Comment by plusvic** [comment]
The service has remained flaky for a while, with some checks running and some failing. It should be working fine now.

**Comment by DanielRuf** [comment]
Confirmed, it works again.

Thank you very much for taking the time to fix this.

Is it helpful, when I reopen if it happens again or do you have an eye on it using some monitoring solution?

Not that I bother you too much with such rather small problems.

**Comment by plusvic** [comment]
Yes, it's useful. Sometimes we notice the issue ourselves, but some times it goes unnoticed. This is an opportunity to set up better monitoring.
