### ISSUE TITLE
Raise limit of false positives

### ISSUE THREAD

**Issue by ruppde** [VirusTotal/yara-ci-issues#18]
hello,

would it be possible to raise the limit of false positives shown? it's about 200 at the moment which is quickly reached with big rulesets. and it's not like some more kilobytes of output should be a problem nowadays.

```
False positives found

1052023 files from the [NSRL](https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl) were scanned, 2004 were detected.
...
and 1812 more ...
```

best regards
arnim

**Comment by Zohiartze** [comment]
The output is limited by GitHub, it cannot exceed 65535 characters, I'm sorry.
