### ISSUE TITLE
github enterprise

### ISSUE THREAD

**Issue by metasyn** [VirusTotal/yara-ci-issues#4]
hello virus total folks,

is there a way that yara-ci can be installed for github enterprise customers?

best,
xander

**Comment by plusvic** [comment]
I would say that the answer is no, but I'm not 100% sure. There are some Github apps that are compatible with Github Enterprise, but I think that requires the application to be prepared for that.

**Comment by metasyn** [comment]
hi victor! thank you for your response. its neat to meet you online 👋 

i see. we would like to use it, and may find a way to do so with non-enterprise github, but would prefer to use with github enterprise if possible. i will close this issue given your response.
