### ISSUE TITLE
Feature idea: Show more info in  false positives list

### ISSUE THREAD

**Issue by ruppde** [VirusTotal/yara-ci-issues#5]
hello,

it would be nice to see more info in the false positives list like e.g. filesize and file type because that helps in quickly getting an overview if these conditions could be used to improve the rule without clicking on all the files.

regards
arnim

**Comment by Zohiartze** [comment]
We have rolled out a new YARA-CI version that shows the file type and size of each match of the false positives test, so I'm closing this. Thank you for your suggestion!

**Comment by ruppde** [comment]
thx
