### ISSUE TITLE
job seems to hang / not start

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara-ci-issues#6]
Last time (11th of September) they still worked. Now they don't.

<img width="663" alt="Bildschirmfoto 2021-09-26 um 20 10 54" src="https://user-images.githubusercontent.com/827205/134819286-2ce4bc7b-78d9-46ba-9a46-cb2b5da7e77b.png">

**Comment by Zohiartze** [comment]
Hi Daniel, thank you for reporting this issue. We have deployed a fix and now it is running ok according to my tests.

**Comment by DanielRuf** [comment]
Thanks for the swift reply @Zohiartze.

But now it seems the service does not complain regarding rules, which contain chinese or unicode characters as strings. This did work before and looks like a regression to me.

> non-ascii character "\xe7"

See also https://github.com/VirusTotal/yara-ci-issues/issues/3

As yara 4.2 is stilol not released (see https://github.com/VirusTotal/yara/releases) I wonder why this check fails again now.

**Comment by DanielRuf** [comment]
Closing this and checking if there is a solution for the new issue at https://github.com/VirusTotal/yara/wiki/Unicode-characters-in-YARA

**Comment by plusvic** [comment]
Hi @DanielRuf we pulled back from the decision of allowing only ascii characters in strings, as too many people had unicode strings in their rules. The plan is allowing only UTF-8, as a tradeoff between supporting existing rules and solving the problem described at  https://github.com/VirusTotal/yara/wiki/Unicode-characters-in-YARA

**Comment by DanielRuf** [comment]
Hi @plusvic,

thanks for the clarification. I totally understand the reasoning behind the past changes and the issues now.

In my case I'm converting the problematic strings with a few lines of Python and document the original value as comment in the affected rules:

```python
import sys
data = sys.stdin.read()
encoded = data.strip().encode(encoding="utf-8", errors="strict")
print(encoded)
```

usage:

```
echo 时| python3 scripts/unicode2ascii.py
```

result:

```
b'\xe6\x97\xb6'
```

**Comment by DanielRuf** [comment]
From a personal standpoint, I would expect backwards-incompatible changes / breaking changes like this in a new major version if yara follows SemVer =)
