### ISSUE TITLE
job seems to hang (again)

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara-ci-issues#7]
<img width="650" alt="Bildschirmfoto 2021-10-07 um 18 17 42" src="https://user-images.githubusercontent.com/827205/136424087-bbb2d2fc-4091-4380-87e9-26fe70663c7b.png">

Should I simply push-force the same commit again to trigger a new build or should I wait until this is fixed?

**Comment by DanielRuf** [comment]
> trigger a new build

This does not seem to make any difference. All builds are not finishing now.

**Comment by Zohiartze** [comment]
Hi @DanielRuf, due to a bad deployment some false positives checks got hang yesterday and they will never end. As you suggest, you will have to commit the changes again to re-run the checks.

**Comment by DanielRuf** [comment]
> Hi @DanielRuf, due to a bad deployment some false positives checks got hang yesterday and they will never end. As you suggest, you will have to commit the changes again to re-run the checks.

Thanks, this seems to be the case. I've tried again and now it works. Thank you very much =)
